Safa.Web/Controllers/Cashbook/CashbookController.cs
using LanguageExt.UnsafeValueAccess;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Safa.Application;
using Safa.Domain.Types;
using Safa.Web.Models;
using Safa.WebUi;

namespace Safa.Web.Controllers.Cashbook;

[Authorize]
[Route("cashbook")]
public class CashbookController : Controller
{
    private readonly ITransactionRepository transactionRepository;
    private readonly IHttpContextAccessor httpContextAccessor;

    public CashbookController(
        ITransactionRepository transactionRepository,
        IHttpContextAccessor httpContextAccessor)
    {
        this.transactionRepository = transactionRepository;
        this.httpContextAccessor = httpContextAccessor;
    }
    
    [HttpGet("")]
    public async Task<IActionResult> Index()
    {
        var userId = this.httpContextAccessor.HttpContext!.User.GetId();
        if (userId.IsNone)
        {
            return View(new CashbookViewModel(
                new List<Transaction>(),
                new AccountSummary(
                    Amount.Zero, 
                    Amount.Zero, 
                    Amount.Zero)));
        }

        var transactions = await transactionRepository
            .GetAll(userId)
            .Match(
                x => x,
                () => new List<Transaction>());
        
        //TODO: DELETE AFTER IMPLEMENTING ACCOUNT SUMMARY
        var savingFraction = Fraction.TryCreate(0.75m)
            .Match(
                fraction => fraction,
                Fraction.Zero);
        var savingPreferences = new SavingPreferences(savingFraction);

        var accountSummary = AccountSummary.CreateFromTransactions(transactions, savingPreferences);
        
        var cashbookViewModel = new CashbookViewModel(
            transactions,
            accountSummary);
        
        return View(cashbookViewModel);
    }
    
    [HttpGet("Create")]
    public IActionResult Create()
    {
        return View();
    }
    
    [HttpPost("Create")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(TransactionRequest transaction)
    {
        var userId = this.httpContextAccessor.HttpContext!.User.GetId();
        
        if (this.ModelState.IsValid && userId.IsSome)
        {
            await this.transactionRepository.Create(transaction, userId.ValueUnsafe());
            return RedirectToAction("Index");
        }
        
        return View(transaction);
    }
    
    [HttpGet("Edit/{id}")]
    public async Task<IActionResult> Edit(Guid id)
    {
        var userId = this.httpContextAccessor.HttpContext!.User.GetId();
        if (userId.IsNone)
        {
            return RedirectToAction("Index");
        }

        var transaction = await this.transactionRepository.GetBy(id, userId.ValueUnsafe());
        return transaction.Match<IActionResult>(
            View,
            () => RedirectToAction("Index"));
    }
    
    [HttpPost("Edit/{id}")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(TransactionRequest transaction)
    {
        var userId = this.httpContextAccessor.HttpContext!.User.GetId();
        
        if (this.ModelState.IsValid && userId.IsSome)
        {
            await this.transactionRepository.Update(transaction, userId.ValueUnsafe());
            return RedirectToAction("Index");
        }
        
        return View(transaction);
    }
    
    [HttpGet("delete/{id}")]
    public async Task<IActionResult> Delete(Guid id)
    {
        var userId = this.httpContextAccessor.HttpContext!.User.GetId();
        if (userId.IsNone)
        {
            return RedirectToAction("Index");
        }

        var transaction = await this.transactionRepository.GetBy(id, userId.ValueUnsafe());
        return transaction.Match<IActionResult>(
            View,
            () => RedirectToAction("Index"));
    }
    
    // Change to Transaction instead of TransactionRequest? Might go hand-in-hand with using a service
    [HttpPost("delete/{id}")]
    public async Task<IActionResult> Delete(TransactionRequest transaction)
    {
        var userId = this.httpContextAccessor.HttpContext!.User.GetId();
        
        if (this.ModelState.IsValid && userId.IsSome)
        {
            await this.transactionRepository.Delete(transaction, userId.ValueUnsafe());
            return RedirectToAction("Index");
        }
        
        return View(transaction);
    }
}

Safa.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SAFA - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">
    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
            <div class="sidebar-brand-icon rotate-n-15">
                <i class="fas fa-money-bill-wave"></i>
            </div>
            <div class="sidebar-brand-text mx-3">SAFA</div>
        </a>

        <!-- Divider -->
        <hr class="sidebar-divider my-0">

        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                <i class="fas fa-fw fa-tachometer-alt"></i><span>Dashboard</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Heading -->
        <div class="sidebar-heading">
            Something
        </div>

        <!-- Nav Item - Tables -->
        <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Cashbook" asp-action="Index">
                <i class="fas fa-fw fa-table"></i><span>Cashbook</span>
            </a>
        </li>

        <!-- Divider -->
        <hr class="sidebar-divider">

        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
            <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

        <!-- Main Content -->
        <div id="content">

            <!-- Topbar -->
            <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                <!-- Sidebar Toggle (Topbar) -->
                <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                    <i class="fa fa-bars"></i>
                </button>

                <!-- Topbar Navbar -->
                <ul class="navbar-nav ml-auto">

                    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                    <li class="nav-item dropdown no-arrow d-sm-none">
                        <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-search fa-fw"></i>
                        </a>
                        <!-- Dropdown - Messages -->
                        <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                             aria-labelledby="searchDropdown">
                            <form class="form-inline mr-auto w-100 navbar-search">
                                <div class="input-group">
                                    <input type="text" class="form-control bg-light border-0 small"
                                           placeholder="Search for..." aria-label="Search"
                                           aria-describedby="basic-addon2">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary" type="button">
                                            <i class="fas fa-search fa-sm"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </li>

                    <!-- TODO: Implement when notifications is supported -->

                    <!-- Nav Item - Alerts -->
                    <!-- <li class="nav-item dropdown no-arrow mx-1">
                    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-bell fa-fw"></i> -->
                    <!-- Counter - Alerts -->
                    <!-- <span class="badge badge-danger badge-counter">3+</span>
                    </a> -->
                    <!-- Dropdown - Alerts -->
                    <!-- <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                              aria-labelledby="alertsDropdown">
                        <h6 class="dropdown-header">
                            Alerts Center
                        </h6>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <div class="mr-3">
                                <div class="icon-circle bg-warning">
                                    <i class="fas fa-exclamation-triangle text-white"></i>
                                </div>
                            </div>
                            <div>
                                <div class="small text-gray-500">December 2, 2019</div>
                                Spending Alert: We've noticed unusually high spending for your account.
                            </div>
                        </a>
                        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                    </div>
                    </li> -->

                    <div class="topbar-divider d-none d-sm-block"></div>

                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="mr-2 d-none d-lg-inline text-gray-600 small">Hi @User.Identity?.Name</span>
                            <img class="img-profile rounded-circle"
                                 src="img/undraw_profile.svg">
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                             aria-labelledby="userDropdown">
                            <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Manage/Index">
                                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                Profile settings
                            </a>

                            <!-- TODO: Implement when supporting activity log -->

                            <!-- <a class="dropdown-item" href="#">
                                <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                Activity Log
                            </a> -->
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                Logout
                            </a>
                        </div>
                    </li>

                </ul>

            </nav>
            <!-- End of Topbar -->

            <!-- Begin Page Content -->
            <div class="container-fluid">

                <!--TODO: Implement when being able to create reports from cashbook transactions-->

                <!-- Page Heading -->
                <!-- <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
                    <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                                                                                                      class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
                </div> -->

                @RenderBody()

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->

    </div>
    <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
</a>

<!-- Bootstrap core JavaScript-->
<script src="~/vendor/jquery/jquery.min.js"></script>
<script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="~/js/sb-admin-2.min.js"></script>

<!-- Page level plugins -->
<script src="~/vendor/chart.js/Chart.min.js"></script>

<!-- Page level custom scripts -->
<script src="~/js/demo/chart-area-demo.js"></script>
<script src="~/js/demo/chart-pie-demo.js"></script>

</body>

</html>
@await RenderSectionAsync("Scripts", required: false)